name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # Change to your main development branch if needed

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2.18.0
        with:
          channel: stable

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Install Dependencies
        run: flutter pub get
        working-directory: flutter_app

      - name: Build Flutter Web
        run: flutter build web --release --base-href="/Crisscross-Design/"
        working-directory: flutter_app
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          branch: gh-pages
          folder: flutter_app/build/web
          clean: true  # Remove previous files before deploying



          
